name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@2b0040e59869e408a94f1e92e67fa47035c50336 # main
        with:
          repository: openstack/cinder
          ref: 188374701a5cb6c44e333678db020fc8bbc0f108 # stable/2025.2

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@2b0040e59869e408a94f1e92e67fa47035c50336 # main
        with:
          image-name: cinder
          build-contexts: cinder=openstack/cinder
          push: ${{ github.event_name != 'pull_request' }}
