name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@main
        with:
          repository: openstack/cinder
          ref: 455d8710980a7ddc399f4eb579af55f6fd929f2d # master

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@main
        with:
          image-name: cinder
          build-contexts: cinder=openstack/cinder
          push: ${{ github.event_name != 'pull_request' }}
